"""Self-building tool handler: propose_connector."""

import json
import logging

logger = logging.getLogger("alfe.tools.self_build")


def handle_propose_connector(inp: dict, user_id: str, pending_approvals: list) -> str:
    """Generate a BaseConnector subclass scaffold and queue it as a code proposal."""
    connector_id = inp["connector_id"]
    description = inp["description"]
    connector_type = inp.get("connector_type", "external_service")
    auth_method = inp.get("auth_method", "api_key")
    env_vars = inp.get("env_vars", [f"{connector_id.upper()}_API_KEY"])
    tools_spec = inp.get("tools", [])

    class_name = "".join(w.capitalize() for w in connector_id.split("_")) + "Connector"

    # Build tool definitions
    tool_defs = []
    tool_handlers = []
    for t in tools_spec:
        tname = t.get("name", f"{connector_id}_action")
        tdesc = t.get("description", "")
        params = t.get("params", [])
        props = {p: {"type": "string"} for p in params}
        req = json.dumps(params)
        tool_defs.append(f"""            ToolDefinition(
                name="{tname}",
                description="{tdesc}",
                input_schema={{
                    "type": "object",
                    "properties": {json.dumps(props)},
                    "required": {req},
                }},
                approval_tier="autonomous",
            ),""")
        tool_handlers.append(f"""            elif name == "{tname}":
                # TODO: implement {tname}
                return ConnectorResult(success=False, content="Not yet implemented: {tname}")""")

    tools_block = "\n".join(tool_defs) if tool_defs else f"""            ToolDefinition(
                name="{connector_id}_status",
                description="Get the status of the {connector_id} connection.",
                input_schema={{"type": "object", "properties": {{}}}},
                approval_tier="autonomous",
            ),"""

    handlers_block = "\n".join(tool_handlers) if tool_handlers else f"""            elif name == "{connector_id}_status":
                return ConnectorResult(success=True, content="Connected to {connector_id}.")"""

    env_inits = "\n".join(
        f'        self._{v.lower()} = self._env("{v}") or ""'
        for v in env_vars
    )

    env_check = " and ".join(f"self._{v.lower()}" for v in env_vars) if env_vars else "True"

    code = f'''"""
Alf-E {connector_id} connector — auto-generated scaffold.
Generated by Alf-E self-building loop. Fill in TODO sections before approving.

Auth: {auth_method}
Env vars required: {", ".join(env_vars)}
"""

import logging
from engine.connectors.base import BaseConnector, ToolDefinition, ConnectorResult

logger = logging.getLogger("alfe.connector.{connector_id}")


class {class_name}(BaseConnector):
    """{ description }"""

    connector_id   = "{connector_id}"
    connector_type = "{connector_type}"
    description    = "{description}"

    def __init__(self, config: dict):
        super().__init__(config)
{env_inits}

    def connect(self) -> bool:
        if not ({env_check}):
            logger.error("{connector_id}: missing required environment variables")
            return False
        # TODO: test the connection (e.g. make a lightweight API call)
        logger.info("{connector_id} connector connected.")
        return True

    def disconnect(self) -> None:
        self.connected = False

    def health_check(self) -> bool:
        # TODO: implement a lightweight health check
        return self.connected

    def get_tools(self) -> list[ToolDefinition]:
        return [
{tools_block}
        ]

    def execute_tool(self, name: str, inp: dict, user_id: str = "fraser") -> ConnectorResult:
        try:
            if False:
                pass
{handlers_block}
            else:
                return ConnectorResult(success=False, content=f"Unknown tool: {{name}}")
        except Exception as e:
            logger.error(f"{connector_id}.execute_tool({{name}}) error: {{e}}")
            return ConnectorResult(success=False, content=f"Error: {{e}}")
'''

    proposal = {
        "type": "code_proposal",
        "connector_id": connector_id,
        "class_name": class_name,
        "description": description,
        "file_path": f"engine/connectors/{connector_id}.py",
        "code": code,
        "proposed_by": user_id,
    }
    pending_approvals.append(proposal)

    tool_names = [t.get("name", "?") for t in tools_spec] if tools_spec else [f"{connector_id}_status"]
    return (
        f"Draft connector ready for review!\n\n"
        f"  File:    engine/connectors/{connector_id}.py\n"
        f"  Class:   {class_name}\n"
        f"  Tools:   {', '.join(tool_names)}\n"
        f"  Auth:    {auth_method}\n"
        f"  Env:     {', '.join(env_vars)}\n\n"
        f"The code is queued — approve it in the UI to write the file, commit, and reload."
    )
