#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
#  Alf-E Installer — run this on any Linux box or HA OS terminal
#
#  Usage:
#    curl -sSL https://raw.githubusercontent.com/majorfrazer/alf-e/main/scripts/install.sh | bash
#
#  What it does:
#    1. Checks for Docker (installs if missing on Debian/Ubuntu)
#    2. Creates /opt/alfe/ with docker-compose.yml
#    3. Pulls the Alf-E image from GHCR
#    4. Starts Alf-E + Watchtower (auto-updates nightly)
#    5. Prints the URL to open the setup wizard
# ═══════════════════════════════════════════════════════════════════

set -euo pipefail

ALFE_IMAGE="ghcr.io/majorfrazer/alf-e:latest"
ALFE_DIR="/opt/alfe"
ALFE_PORT="8099"
BOLD="\033[1m"
CYAN="\033[36m"
GREEN="\033[32m"
YELLOW="\033[33m"
RED="\033[31m"
RESET="\033[0m"

banner() { echo -e "\n${BOLD}${CYAN}▶ $1${RESET}"; }
ok()     { echo -e "  ${GREEN}✓${RESET} $1"; }
warn()   { echo -e "  ${YELLOW}⚠${RESET}  $1"; }
err()    { echo -e "  ${RED}✗${RESET}  $1"; exit 1; }

echo ""
echo -e "${BOLD}${CYAN}"
echo "  ╔═══════════════════════════════╗"
echo "  ║        A L F - E             ║"
echo "  ║   Personal AI Agent Setup    ║"
echo "  ╚═══════════════════════════════╝"
echo -e "${RESET}"

# ── 1. Check / install Docker ─────────────────────────────────────────────────
banner "Checking Docker"

if command -v docker &>/dev/null; then
    ok "Docker $(docker --version | awk '{print $3}' | tr -d ',')"
else
    warn "Docker not found — installing..."
    if command -v apt-get &>/dev/null; then
        apt-get update -qq
        apt-get install -y -qq ca-certificates curl gnupg lsb-release
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
            | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
            https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
            > /etc/apt/sources.list.d/docker.list
        apt-get update -qq
        apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
        ok "Docker installed"
    else
        err "Could not auto-install Docker — please install it manually: https://docs.docker.com/engine/install/"
    fi
fi

if ! docker compose version &>/dev/null; then
    err "Docker Compose plugin not found. Install Docker Desktop or the compose plugin."
fi

# ── 2. Create install directory ───────────────────────────────────────────────
banner "Creating $ALFE_DIR"
mkdir -p "$ALFE_DIR"
ok "Directory ready"

# ── 3. Write docker-compose.yml ───────────────────────────────────────────────
banner "Writing docker-compose.yml"

cat > "$ALFE_DIR/docker-compose.yml" << COMPOSE
# Alf-E — generated by install.sh
# To update manually: docker compose pull && docker compose up -d

networks:
  alfe_net:
    driver: bridge

volumes:
  alfe_data:

services:

  alf-e:
    image: ${ALFE_IMAGE}
    container_name: alf-e
    restart: unless-stopped
    ports:
      - "${ALFE_PORT}:8000"
    volumes:
      - alfe_data:/data
    environment:
      - ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=\${GOOGLE_API_KEY:-}
      - HA_API_TOKEN=\${HA_API_TOKEN:-}
      - ALFE_API_TOKEN=\${ALFE_API_TOKEN:-}
      - ALFE_DATA_DIR=/data
    networks:
      - alfe_net

  # Watchtower — pulls new Alf-E image nightly and restarts automatically
  watchtower:
    image: containrrr/watchtower:latest
    container_name: alfe-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_NOTIFICATION_REPORT=false
    command: alf-e
    networks:
      - alfe_net
COMPOSE

ok "docker-compose.yml written"

# ── 4. Pull image ─────────────────────────────────────────────────────────────
banner "Pulling Alf-E image (this may take a minute…)"
docker pull "$ALFE_IMAGE"
ok "Image ready"

# ── 5. Start services ─────────────────────────────────────────────────────────
banner "Starting Alf-E"
cd "$ALFE_DIR"
docker compose up -d
ok "Alf-E is running"

# ── 6. Get local IP ───────────────────────────────────────────────────────────
LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}  ✓ Alf-E is installed and running!${RESET}"
echo ""
echo -e "  Open the setup wizard in your browser:"
echo -e "  ${BOLD}${CYAN}  http://${LOCAL_IP}:${ALFE_PORT}/setup${RESET}"
echo ""
echo -e "  To manage Alf-E:"
echo -e "    cd $ALFE_DIR"
echo -e "    docker compose logs -f alf-e    # live logs"
echo -e "    docker compose restart alf-e    # restart"
echo -e "    docker compose pull && docker compose up -d  # manual update"
echo ""
echo -e "  Updates are automatic — Watchtower checks nightly at 3am."
echo ""
